FROM node:22-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    autoconf \
    automake \
    zlib1g-dev \
    libpng-dev \
    nasm \
    bash \
    libvips-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN NODE_ENV=production npm run build

EXPOSE 1337
CMD ["npm", "run", "start"]
